// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServerIP(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddServerIP'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CheckPort(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CheckPort'](arg1, arg2, arg3, arg4);
}

export function CloseServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CloseServer'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateSSHClient(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSSHClient'](arg1, arg2, arg3, arg4);
}

export function Fetchost(arg1) {
  return window['go']['main']['App']['Fetchost'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Install(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Install'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenNewWindow() {
  return window['go']['main']['App']['OpenNewWindow']();
}

export function RunServer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RunServer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Setprivatekey(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Setprivatekey'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Uninstall(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Uninstall'](arg1, arg2, arg3, arg4, arg5);
}

export function UploadFile(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UploadFolder(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UploadFolder'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UploadPrivatekey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadPrivatekey'](arg1, arg2, arg3, arg4);
}
