// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPort(arg1, arg2) {
  return window['go']['main']['App']['CheckPort'](arg1, arg2);
}

export function CloseServer(arg1, arg2) {
  return window['go']['main']['App']['CloseServer'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Install(arg1, arg2) {
  return window['go']['main']['App']['Install'](arg1, arg2);
}

export function RunServer(arg1, arg2) {
  return window['go']['main']['App']['RunServer'](arg1, arg2);
}
