// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServerIP(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CheckPort(arg1:string,arg2:string):Promise<string>;

export function CloseServer(arg1:string,arg2:string):Promise<string>;

export function Fetchost(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Install(arg1:string,arg2:string):Promise<string>;

export function RunServer(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Setprivatekey(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Uninstall(arg1:string,arg2:string):Promise<string>;
