// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServerIP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddServerIP'](arg1, arg2, arg3, arg4);
}

export function CheckPort(arg1, arg2) {
  return window['go']['main']['App']['CheckPort'](arg1, arg2);
}

export function CloseServer(arg1, arg2) {
  return window['go']['main']['App']['CloseServer'](arg1, arg2);
}

export function Fetchost(arg1) {
  return window['go']['main']['App']['Fetchost'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Install(arg1, arg2) {
  return window['go']['main']['App']['Install'](arg1, arg2);
}

export function RunServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunServer'](arg1, arg2, arg3);
}

export function Setprivatekey(arg1, arg2, arg3) {
  return window['go']['main']['App']['Setprivatekey'](arg1, arg2, arg3);
}

export function Uninstall(arg1, arg2) {
  return window['go']['main']['App']['Uninstall'](arg1, arg2);
}
