// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ssh} from '../models';

export function AddServerIP(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<string>;

export function CheckPort(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CloseServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function CreateSSHClient(arg1:string,arg2:string,arg3:string,arg4:string):Promise<ssh.Client>;

export function Fetchost(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Install(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function OpenNewWindow():Promise<void>;

export function RunServer(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function Setprivatekey(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function Uninstall(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function UploadFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Uint8Array,arg6:string):Promise<string>;

export function UploadFolder(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function UploadPrivatekey(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
